language: node_js
node_js:
    - node
    - iojs
before_script:
    - mysql -e 'CREATE DATABASE otserv;'
    - curl https://raw.githubusercontent.com/ranisalt/forgottenserver/master/schema.sql -O
    - mysql -u travis otserv < schema.sql
    - npm i -g istanbul istanbul-coveralls mocha mocha-lcov-reporter
after_success:
    - istanbul cover _mocha -- -R mocha-lcov-reporter ./test/*.js
    - istanbul-coveralls
